---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.3.0
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[motd::default]
    attributes:
